insert into USER(first_name, last_name, email, password) values ("Pera", "Peric", "perap@gmail.com", "12345678")
insert into USER(first_name, last_name, email, password) values ("Janko", "Jankovic", "jankoj@gmail.com", "12345678")
insert into USER(first_name, last_name, email, password) values ("Marko", "Markovic", "mmarko@gmail.com", "12345678")
insert into USER(first_name, last_name, email, password) values ("Jovan", "Jovanovic", "jjovan@gmail.com", "12345678")

insert into ROLE(name) values ("Admin")
insert into ROLE(name) values ("Bank Manager")
insert into ROLE(name) values ("Client Manager")

insert into PERMISSION(name) values ("AddBank")
insert into PERMISSION(name) values ("UpdateBank")
insert into PERMISSION(name) values ("DeleteBank")
insert into PERMISSION(name) values ("AddBankAccount")
insert into PERMISSION(name) values ("UpdateBankAccount")
insert into PERMISSION(name) values ("DeleteBankAccount")

insert into USERS_ROLES(user_id, role_id) values (3, 1)
insert into USERS_ROLES(user_id, role_id) values (1, 2)
insert into USERS_ROLES(user_id, role_id) values (2, 3)
insert into USERS_ROLES(user_id, role_id) values (3, 2)
insert into USERS_ROLES(user_id, role_id) values (4, 3)

insert into ROLES_PERMISSIONS(role_id, permission_id) values (1, 1)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (1, 2)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (1, 3)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (2, 4)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (2, 5)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (2, 6)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (3, 4)
insert into ROLES_PERMISSIONS(role_id, permission_id) values (3, 5)