//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.15 at 10:11:21 PM CEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMT910Request }
     * 
     */
    public GetMT910Request createGetMT910Request() {
        return new GetMT910Request();
    }

    /**
     * Create an instance of {@link GetMT9X0Request }
     * 
     */
    public GetMT9X0Request createGetMT9X0Request() {
        return new GetMT9X0Request();
    }

    /**
     * Create an instance of {@link GetMT9X0Response }
     * 
     */
    public GetMT9X0Response createGetMT9X0Response() {
        return new GetMT9X0Response();
    }

    /**
     * Create an instance of {@link GetMOneZeroThreeRequest }
     * 
     */
    public GetMOneZeroThreeRequest createGetMOneZeroThreeRequest() {
        return new GetMOneZeroThreeRequest();
    }

    /**
     * Create an instance of {@link ImportNalogZaPlacanjeRequest }
     * 
     */
    public ImportNalogZaPlacanjeRequest createImportNalogZaPlacanjeRequest() {
        return new ImportNalogZaPlacanjeRequest();
    }

    /**
     * Create an instance of {@link IzvodRequest }
     * 
     */
    public IzvodRequest createIzvodRequest() {
        return new IzvodRequest();
    }

    /**
     * Create an instance of {@link GetMOneZeroThreeResponse }
     * 
     */
    public GetMOneZeroThreeResponse createGetMOneZeroThreeResponse() {
        return new GetMOneZeroThreeResponse();
    }

    /**
     * Create an instance of {@link GetMT900Request }
     * 
     */
    public GetMT900Request createGetMT900Request() {
        return new GetMT900Request();
    }

    /**
     * Create an instance of {@link GetM102Response }
     * 
     */
    public GetM102Response createGetM102Response() {
        return new GetM102Response();
    }

    /**
     * Create an instance of {@link ImportNalogZaPlacanjeResponse }
     * 
     */
    public ImportNalogZaPlacanjeResponse createImportNalogZaPlacanjeResponse() {
        return new ImportNalogZaPlacanjeResponse();
    }

    /**
     * Create an instance of {@link IzvodResponse }
     * 
     */
    public IzvodResponse createIzvodResponse() {
        return new IzvodResponse();
    }

    /**
     * Create an instance of {@link ZaglavljePreseka }
     * 
     */
    public ZaglavljePreseka createZaglavljePreseka() {
        return new ZaglavljePreseka();
    }

    /**
     * Create an instance of {@link StavkaPreseka }
     * 
     */
    public StavkaPreseka createStavkaPreseka() {
        return new StavkaPreseka();
    }

    /**
     * Create an instance of {@link GetM102Request }
     * 
     */
    public GetM102Request createGetM102Request() {
        return new GetM102Request();
    }

    /**
     * Create an instance of {@link M102StavkaType }
     * 
     */
    public M102StavkaType createM102StavkaType() {
        return new M102StavkaType();
    }

}
